// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	IdentityLink *identityLink
	MemoryItem   *memoryItem
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	IdentityLink = &Q.IdentityLink
	MemoryItem = &Q.MemoryItem
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		IdentityLink: newIdentityLink(db, opts...),
		MemoryItem:   newMemoryItem(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	IdentityLink identityLink
	MemoryItem   memoryItem
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		IdentityLink: q.IdentityLink.clone(db),
		MemoryItem:   q.MemoryItem.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		IdentityLink: q.IdentityLink.replaceDB(db),
		MemoryItem:   q.MemoryItem.replaceDB(db),
	}
}

type queryCtx struct {
	IdentityLink IIdentityLinkDo
	MemoryItem   IMemoryItemDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		IdentityLink: q.IdentityLink.WithContext(ctx),
		MemoryItem:   q.MemoryItem.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
