// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/quailyquaily/mister_morph/db/models"
)

func newIdentityLink(db *gorm.DB, opts ...gen.DOOption) identityLink {
	_identityLink := identityLink{}

	_identityLink.identityLinkDo.UseDB(db, opts...)
	_identityLink.identityLinkDo.UseModel(&models.IdentityLink{})

	tableName := _identityLink.identityLinkDo.TableName()
	_identityLink.ALL = field.NewAsterisk(tableName)
	_identityLink.ExternalKey = field.NewString(tableName, "external_key")
	_identityLink.SubjectID = field.NewString(tableName, "subject_id")
	_identityLink.CreatedAt = field.NewInt64(tableName, "created_at")
	_identityLink.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_identityLink.fillFieldMap()

	return _identityLink
}

type identityLink struct {
	identityLinkDo identityLinkDo

	ALL         field.Asterisk
	ExternalKey field.String
	SubjectID   field.String
	CreatedAt   field.Int64
	UpdatedAt   field.Int64

	fieldMap map[string]field.Expr
}

func (i identityLink) Table(newTableName string) *identityLink {
	i.identityLinkDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i identityLink) As(alias string) *identityLink {
	i.identityLinkDo.DO = *(i.identityLinkDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *identityLink) updateTableName(table string) *identityLink {
	i.ALL = field.NewAsterisk(table)
	i.ExternalKey = field.NewString(table, "external_key")
	i.SubjectID = field.NewString(table, "subject_id")
	i.CreatedAt = field.NewInt64(table, "created_at")
	i.UpdatedAt = field.NewInt64(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *identityLink) WithContext(ctx context.Context) IIdentityLinkDo {
	return i.identityLinkDo.WithContext(ctx)
}

func (i identityLink) TableName() string { return i.identityLinkDo.TableName() }

func (i identityLink) Alias() string { return i.identityLinkDo.Alias() }

func (i identityLink) Columns(cols ...field.Expr) gen.Columns {
	return i.identityLinkDo.Columns(cols...)
}

func (i *identityLink) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *identityLink) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 4)
	i.fieldMap["external_key"] = i.ExternalKey
	i.fieldMap["subject_id"] = i.SubjectID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i identityLink) clone(db *gorm.DB) identityLink {
	i.identityLinkDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i identityLink) replaceDB(db *gorm.DB) identityLink {
	i.identityLinkDo.ReplaceDB(db)
	return i
}

type identityLinkDo struct{ gen.DO }

type IIdentityLinkDo interface {
	gen.SubQuery
	Debug() IIdentityLinkDo
	WithContext(ctx context.Context) IIdentityLinkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIdentityLinkDo
	WriteDB() IIdentityLinkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIdentityLinkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIdentityLinkDo
	Not(conds ...gen.Condition) IIdentityLinkDo
	Or(conds ...gen.Condition) IIdentityLinkDo
	Select(conds ...field.Expr) IIdentityLinkDo
	Where(conds ...gen.Condition) IIdentityLinkDo
	Order(conds ...field.Expr) IIdentityLinkDo
	Distinct(cols ...field.Expr) IIdentityLinkDo
	Omit(cols ...field.Expr) IIdentityLinkDo
	Join(table schema.Tabler, on ...field.Expr) IIdentityLinkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIdentityLinkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIdentityLinkDo
	Group(cols ...field.Expr) IIdentityLinkDo
	Having(conds ...gen.Condition) IIdentityLinkDo
	Limit(limit int) IIdentityLinkDo
	Offset(offset int) IIdentityLinkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIdentityLinkDo
	Unscoped() IIdentityLinkDo
	Create(values ...*models.IdentityLink) error
	CreateInBatches(values []*models.IdentityLink, batchSize int) error
	Save(values ...*models.IdentityLink) error
	First() (*models.IdentityLink, error)
	Take() (*models.IdentityLink, error)
	Last() (*models.IdentityLink, error)
	Find() ([]*models.IdentityLink, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.IdentityLink, err error)
	FindInBatches(result *[]*models.IdentityLink, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.IdentityLink) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIdentityLinkDo
	Assign(attrs ...field.AssignExpr) IIdentityLinkDo
	Joins(fields ...field.RelationField) IIdentityLinkDo
	Preload(fields ...field.RelationField) IIdentityLinkDo
	FirstOrInit() (*models.IdentityLink, error)
	FirstOrCreate() (*models.IdentityLink, error)
	FindByPage(offset int, limit int) (result []*models.IdentityLink, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIdentityLinkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByExternalKey(ctx context.Context, externalKey string) (result *models.IdentityLink, err error)
}

// GetByExternalKey returns an identity link for an external_key.
//
// SELECT * FROM @@table WHERE external_key=@externalKey LIMIT 1;
func (i identityLinkDo) GetByExternalKey(ctx context.Context, externalKey string) (result *models.IdentityLink, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, externalKey)
	generateSQL.WriteString("SELECT * FROM identity_links WHERE external_key=? LIMIT 1; ")

	var executeSQL *gorm.DB
	executeSQL = i.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (i identityLinkDo) Debug() IIdentityLinkDo {
	return i.withDO(i.DO.Debug())
}

func (i identityLinkDo) WithContext(ctx context.Context) IIdentityLinkDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i identityLinkDo) ReadDB() IIdentityLinkDo {
	return i.Clauses(dbresolver.Read)
}

func (i identityLinkDo) WriteDB() IIdentityLinkDo {
	return i.Clauses(dbresolver.Write)
}

func (i identityLinkDo) Session(config *gorm.Session) IIdentityLinkDo {
	return i.withDO(i.DO.Session(config))
}

func (i identityLinkDo) Clauses(conds ...clause.Expression) IIdentityLinkDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i identityLinkDo) Returning(value interface{}, columns ...string) IIdentityLinkDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i identityLinkDo) Not(conds ...gen.Condition) IIdentityLinkDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i identityLinkDo) Or(conds ...gen.Condition) IIdentityLinkDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i identityLinkDo) Select(conds ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i identityLinkDo) Where(conds ...gen.Condition) IIdentityLinkDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i identityLinkDo) Order(conds ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i identityLinkDo) Distinct(cols ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i identityLinkDo) Omit(cols ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i identityLinkDo) Join(table schema.Tabler, on ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i identityLinkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i identityLinkDo) RightJoin(table schema.Tabler, on ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i identityLinkDo) Group(cols ...field.Expr) IIdentityLinkDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i identityLinkDo) Having(conds ...gen.Condition) IIdentityLinkDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i identityLinkDo) Limit(limit int) IIdentityLinkDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i identityLinkDo) Offset(offset int) IIdentityLinkDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i identityLinkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIdentityLinkDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i identityLinkDo) Unscoped() IIdentityLinkDo {
	return i.withDO(i.DO.Unscoped())
}

func (i identityLinkDo) Create(values ...*models.IdentityLink) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i identityLinkDo) CreateInBatches(values []*models.IdentityLink, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i identityLinkDo) Save(values ...*models.IdentityLink) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i identityLinkDo) First() (*models.IdentityLink, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdentityLink), nil
	}
}

func (i identityLinkDo) Take() (*models.IdentityLink, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdentityLink), nil
	}
}

func (i identityLinkDo) Last() (*models.IdentityLink, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdentityLink), nil
	}
}

func (i identityLinkDo) Find() ([]*models.IdentityLink, error) {
	result, err := i.DO.Find()
	return result.([]*models.IdentityLink), err
}

func (i identityLinkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.IdentityLink, err error) {
	buf := make([]*models.IdentityLink, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i identityLinkDo) FindInBatches(result *[]*models.IdentityLink, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i identityLinkDo) Attrs(attrs ...field.AssignExpr) IIdentityLinkDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i identityLinkDo) Assign(attrs ...field.AssignExpr) IIdentityLinkDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i identityLinkDo) Joins(fields ...field.RelationField) IIdentityLinkDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i identityLinkDo) Preload(fields ...field.RelationField) IIdentityLinkDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i identityLinkDo) FirstOrInit() (*models.IdentityLink, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdentityLink), nil
	}
}

func (i identityLinkDo) FirstOrCreate() (*models.IdentityLink, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.IdentityLink), nil
	}
}

func (i identityLinkDo) FindByPage(offset int, limit int) (result []*models.IdentityLink, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i identityLinkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i identityLinkDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i identityLinkDo) Delete(models ...*models.IdentityLink) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *identityLinkDo) withDO(do gen.Dao) *identityLinkDo {
	i.DO = *do.(*gen.DO)
	return i
}
