// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"

	"github.com/quailyquaily/mister_morph/db/models"
)

func newMemoryItem(db *gorm.DB, opts ...gen.DOOption) memoryItem {
	_memoryItem := memoryItem{}

	_memoryItem.memoryItemDo.UseDB(db, opts...)
	_memoryItem.memoryItemDo.UseModel(&models.MemoryItem{})

	tableName := _memoryItem.memoryItemDo.TableName()
	_memoryItem.ALL = field.NewAsterisk(tableName)
	_memoryItem.SubjectID = field.NewString(tableName, "subject_id")
	_memoryItem.Namespace = field.NewString(tableName, "namespace")
	_memoryItem.Key = field.NewString(tableName, "key")
	_memoryItem.Value = field.NewString(tableName, "value")
	_memoryItem.Visibility = field.NewInt(tableName, "visibility")
	_memoryItem.Confidence = field.NewFloat64(tableName, "confidence")
	_memoryItem.Source = field.NewString(tableName, "source")
	_memoryItem.CreatedAt = field.NewInt64(tableName, "created_at")
	_memoryItem.UpdatedAt = field.NewInt64(tableName, "updated_at")

	_memoryItem.fillFieldMap()

	return _memoryItem
}

type memoryItem struct {
	memoryItemDo memoryItemDo

	ALL        field.Asterisk
	SubjectID  field.String
	Namespace  field.String
	Key        field.String
	Value      field.String
	Visibility field.Int
	Confidence field.Float64
	Source     field.String
	CreatedAt  field.Int64
	UpdatedAt  field.Int64

	fieldMap map[string]field.Expr
}

func (m memoryItem) Table(newTableName string) *memoryItem {
	m.memoryItemDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memoryItem) As(alias string) *memoryItem {
	m.memoryItemDo.DO = *(m.memoryItemDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memoryItem) updateTableName(table string) *memoryItem {
	m.ALL = field.NewAsterisk(table)
	m.SubjectID = field.NewString(table, "subject_id")
	m.Namespace = field.NewString(table, "namespace")
	m.Key = field.NewString(table, "key")
	m.Value = field.NewString(table, "value")
	m.Visibility = field.NewInt(table, "visibility")
	m.Confidence = field.NewFloat64(table, "confidence")
	m.Source = field.NewString(table, "source")
	m.CreatedAt = field.NewInt64(table, "created_at")
	m.UpdatedAt = field.NewInt64(table, "updated_at")

	m.fillFieldMap()

	return m
}

func (m *memoryItem) WithContext(ctx context.Context) IMemoryItemDo {
	return m.memoryItemDo.WithContext(ctx)
}

func (m memoryItem) TableName() string { return m.memoryItemDo.TableName() }

func (m memoryItem) Alias() string { return m.memoryItemDo.Alias() }

func (m memoryItem) Columns(cols ...field.Expr) gen.Columns { return m.memoryItemDo.Columns(cols...) }

func (m *memoryItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memoryItem) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 9)
	m.fieldMap["subject_id"] = m.SubjectID
	m.fieldMap["namespace"] = m.Namespace
	m.fieldMap["key"] = m.Key
	m.fieldMap["value"] = m.Value
	m.fieldMap["visibility"] = m.Visibility
	m.fieldMap["confidence"] = m.Confidence
	m.fieldMap["source"] = m.Source
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
}

func (m memoryItem) clone(db *gorm.DB) memoryItem {
	m.memoryItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memoryItem) replaceDB(db *gorm.DB) memoryItem {
	m.memoryItemDo.ReplaceDB(db)
	return m
}

type memoryItemDo struct{ gen.DO }

type IMemoryItemDo interface {
	gen.SubQuery
	Debug() IMemoryItemDo
	WithContext(ctx context.Context) IMemoryItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemoryItemDo
	WriteDB() IMemoryItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemoryItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemoryItemDo
	Not(conds ...gen.Condition) IMemoryItemDo
	Or(conds ...gen.Condition) IMemoryItemDo
	Select(conds ...field.Expr) IMemoryItemDo
	Where(conds ...gen.Condition) IMemoryItemDo
	Order(conds ...field.Expr) IMemoryItemDo
	Distinct(cols ...field.Expr) IMemoryItemDo
	Omit(cols ...field.Expr) IMemoryItemDo
	Join(table schema.Tabler, on ...field.Expr) IMemoryItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemoryItemDo
	Group(cols ...field.Expr) IMemoryItemDo
	Having(conds ...gen.Condition) IMemoryItemDo
	Limit(limit int) IMemoryItemDo
	Offset(offset int) IMemoryItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryItemDo
	Unscoped() IMemoryItemDo
	Create(values ...*models.MemoryItem) error
	CreateInBatches(values []*models.MemoryItem, batchSize int) error
	Save(values ...*models.MemoryItem) error
	First() (*models.MemoryItem, error)
	Take() (*models.MemoryItem, error)
	Last() (*models.MemoryItem, error)
	Find() ([]*models.MemoryItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MemoryItem, err error)
	FindInBatches(result *[]*models.MemoryItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.MemoryItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemoryItemDo
	Assign(attrs ...field.AssignExpr) IMemoryItemDo
	Joins(fields ...field.RelationField) IMemoryItemDo
	Preload(fields ...field.RelationField) IMemoryItemDo
	FirstOrInit() (*models.MemoryItem, error)
	FirstOrCreate() (*models.MemoryItem, error)
	FindByPage(offset int, limit int) (result []*models.MemoryItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemoryItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetAny(ctx context.Context, subjectID string, namespace string, key string) (result *models.MemoryItem, err error)
	GetPublic(ctx context.Context, subjectID string, namespace string, key string) (result *models.MemoryItem, err error)
	ListAny(ctx context.Context, subjectID string, namespace string, prefix string, limit int) (result []*models.MemoryItem, err error)
	ListPublic(ctx context.Context, subjectID string, namespace string, prefix string, limit int) (result []*models.MemoryItem, err error)
	Upsert(ctx context.Context, subjectID string, namespace string, key string, value string, visibility int, confidence *float64, source *string, createdAt int64, updatedAt int64) (err error)
	DeleteKey(ctx context.Context, subjectID string, namespace string, key string) (err error)
	DeleteNamespace(ctx context.Context, subjectID string, namespace string) (err error)
	WipeSubject(ctx context.Context, subjectID string) (err error)
}

// GetAny returns a single memory item (no visibility filtering).
//
// SELECT * FROM @@table WHERE subject_id=@subjectID AND namespace=@namespace AND `key`=@key LIMIT 1;
func (m memoryItemDo) GetAny(ctx context.Context, subjectID string, namespace string, key string) (result *models.MemoryItem, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, subjectID)
	params = append(params, namespace)
	params = append(params, key)
	generateSQL.WriteString("SELECT * FROM memory_items WHERE subject_id=? AND namespace=? AND `key`=? LIMIT 1; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetPublic returns a single public-safe memory item (visibility=public_ok).
//
// SELECT * FROM @@table WHERE subject_id=@subjectID AND namespace=@namespace AND `key`=@key AND visibility=0 LIMIT 1;
func (m memoryItemDo) GetPublic(ctx context.Context, subjectID string, namespace string, key string) (result *models.MemoryItem, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, subjectID)
	params = append(params, namespace)
	params = append(params, key)
	generateSQL.WriteString("SELECT * FROM memory_items WHERE subject_id=? AND namespace=? AND `key`=? AND visibility=0 LIMIT 1; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListAny lists memory items in a namespace (no visibility filtering).
// Pass prefix as "foo%" or empty string.
//
// SELECT * FROM @@table {{where}} subject_id=@subjectID AND namespace=@namespace {{if prefix != ""}} AND `key` LIKE @prefix{{end}}{{end}} ORDER BY updated_at DESC LIMIT @limit;
func (m memoryItemDo) ListAny(ctx context.Context, subjectID string, namespace string, prefix string, limit int) (result []*models.MemoryItem, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM memory_items ")
	var whereSQL0 strings.Builder
	params = append(params, subjectID)
	params = append(params, namespace)
	whereSQL0.WriteString("subject_id=? AND namespace=? ")
	if prefix != "" {
		params = append(params, prefix)
		whereSQL0.WriteString("AND `key` LIKE ? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	params = append(params, limit)
	generateSQL.WriteString("ORDER BY updated_at DESC LIMIT ?; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListPublic lists public-safe memory items in a namespace (visibility=public_ok).
// Pass prefix as "foo%" or empty string.
//
// SELECT * FROM @@table {{where}} subject_id=@subjectID AND namespace=@namespace AND visibility=0 {{if prefix != ""}} AND `key` LIKE @prefix{{end}}{{end}} ORDER BY updated_at DESC LIMIT @limit;
func (m memoryItemDo) ListPublic(ctx context.Context, subjectID string, namespace string, prefix string, limit int) (result []*models.MemoryItem, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM memory_items ")
	var whereSQL0 strings.Builder
	params = append(params, subjectID)
	params = append(params, namespace)
	whereSQL0.WriteString("subject_id=? AND namespace=? AND visibility=0 ")
	if prefix != "" {
		params = append(params, prefix)
		whereSQL0.WriteString("AND `key` LIKE ? ")
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	params = append(params, limit)
	generateSQL.WriteString("ORDER BY updated_at DESC LIMIT ?; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// Upsert writes the latest value for (subject_id, namespace, key).
//
// INSERT INTO @@table (subject_id, namespace, `key`, value, visibility, confidence, source, created_at, updated_at) VALUES (@subjectID, @namespace, @key, @value, @visibility, @confidence, @source, @createdAt, @updatedAt) ON CONFLICT(subject_id, namespace, `key`) DO UPDATE SET value=@value, visibility=@visibility, confidence=@confidence, source=@source, updated_at=@updatedAt;
func (m memoryItemDo) Upsert(ctx context.Context, subjectID string, namespace string, key string, value string, visibility int, confidence *float64, source *string, createdAt int64, updatedAt int64) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, subjectID)
	params = append(params, namespace)
	params = append(params, key)
	params = append(params, value)
	params = append(params, visibility)
	params = append(params, confidence)
	params = append(params, source)
	params = append(params, createdAt)
	params = append(params, updatedAt)
	params = append(params, value)
	params = append(params, visibility)
	params = append(params, confidence)
	params = append(params, source)
	params = append(params, updatedAt)
	generateSQL.WriteString("INSERT INTO memory_items (subject_id, namespace, `key`, value, visibility, confidence, source, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(subject_id, namespace, `key`) DO UPDATE SET value=?, visibility=?, confidence=?, source=?, updated_at=?; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteKey deletes one memory item by key.
//
// DELETE FROM @@table WHERE subject_id=@subjectID AND namespace=@namespace AND `key`=@key;
func (m memoryItemDo) DeleteKey(ctx context.Context, subjectID string, namespace string, key string) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, subjectID)
	params = append(params, namespace)
	params = append(params, key)
	generateSQL.WriteString("DELETE FROM memory_items WHERE subject_id=? AND namespace=? AND `key`=?; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// DeleteNamespace deletes all memory items in a namespace for a subject.
//
// DELETE FROM @@table WHERE subject_id=@subjectID AND namespace=@namespace;
func (m memoryItemDo) DeleteNamespace(ctx context.Context, subjectID string, namespace string) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, subjectID)
	params = append(params, namespace)
	generateSQL.WriteString("DELETE FROM memory_items WHERE subject_id=? AND namespace=?; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

// WipeSubject deletes all memory items for a subject.
//
// DELETE FROM @@table WHERE subject_id=@subjectID;
func (m memoryItemDo) WipeSubject(ctx context.Context, subjectID string) (err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, subjectID)
	generateSQL.WriteString("DELETE FROM memory_items WHERE subject_id=?; ")

	var executeSQL *gorm.DB
	executeSQL = m.UnderlyingDB().Exec(generateSQL.String(), params...) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (m memoryItemDo) Debug() IMemoryItemDo {
	return m.withDO(m.DO.Debug())
}

func (m memoryItemDo) WithContext(ctx context.Context) IMemoryItemDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memoryItemDo) ReadDB() IMemoryItemDo {
	return m.Clauses(dbresolver.Read)
}

func (m memoryItemDo) WriteDB() IMemoryItemDo {
	return m.Clauses(dbresolver.Write)
}

func (m memoryItemDo) Session(config *gorm.Session) IMemoryItemDo {
	return m.withDO(m.DO.Session(config))
}

func (m memoryItemDo) Clauses(conds ...clause.Expression) IMemoryItemDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memoryItemDo) Returning(value interface{}, columns ...string) IMemoryItemDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memoryItemDo) Not(conds ...gen.Condition) IMemoryItemDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memoryItemDo) Or(conds ...gen.Condition) IMemoryItemDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memoryItemDo) Select(conds ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memoryItemDo) Where(conds ...gen.Condition) IMemoryItemDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memoryItemDo) Order(conds ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memoryItemDo) Distinct(cols ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memoryItemDo) Omit(cols ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memoryItemDo) Join(table schema.Tabler, on ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memoryItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memoryItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memoryItemDo) Group(cols ...field.Expr) IMemoryItemDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memoryItemDo) Having(conds ...gen.Condition) IMemoryItemDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memoryItemDo) Limit(limit int) IMemoryItemDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memoryItemDo) Offset(offset int) IMemoryItemDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memoryItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemoryItemDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memoryItemDo) Unscoped() IMemoryItemDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memoryItemDo) Create(values ...*models.MemoryItem) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memoryItemDo) CreateInBatches(values []*models.MemoryItem, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memoryItemDo) Save(values ...*models.MemoryItem) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memoryItemDo) First() (*models.MemoryItem, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.MemoryItem), nil
	}
}

func (m memoryItemDo) Take() (*models.MemoryItem, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.MemoryItem), nil
	}
}

func (m memoryItemDo) Last() (*models.MemoryItem, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.MemoryItem), nil
	}
}

func (m memoryItemDo) Find() ([]*models.MemoryItem, error) {
	result, err := m.DO.Find()
	return result.([]*models.MemoryItem), err
}

func (m memoryItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.MemoryItem, err error) {
	buf := make([]*models.MemoryItem, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memoryItemDo) FindInBatches(result *[]*models.MemoryItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memoryItemDo) Attrs(attrs ...field.AssignExpr) IMemoryItemDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memoryItemDo) Assign(attrs ...field.AssignExpr) IMemoryItemDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memoryItemDo) Joins(fields ...field.RelationField) IMemoryItemDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memoryItemDo) Preload(fields ...field.RelationField) IMemoryItemDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memoryItemDo) FirstOrInit() (*models.MemoryItem, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.MemoryItem), nil
	}
}

func (m memoryItemDo) FirstOrCreate() (*models.MemoryItem, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.MemoryItem), nil
	}
}

func (m memoryItemDo) FindByPage(offset int, limit int) (result []*models.MemoryItem, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memoryItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memoryItemDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memoryItemDo) Delete(models ...*models.MemoryItem) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memoryItemDo) withDO(do gen.Dao) *memoryItemDo {
	m.DO = *do.(*gen.DO)
	return m
}
